version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: weops_saas
      MYSQL_USER: root
      MYSQL_PASSWORD: jIUxdSqwQJss
    ports:
      - "3306:3306"
    volumes:
      - /path/to/mysql/data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"

  casbin-mesh:
    image: casbin-mesh:latest
    container_name: casbin-mesh-container
    environment:
      # Casbin Mesh configuration environment variables
      CASBIN_MESH_DATABASE: mysql
      CASBIN_MESH_DATABASE_CONNECTION_STRING: "mysql:mysql:3306?dbname=weops_saas&username=root&password=jIUxdSqwQJss"
      CASBIN_MESH_REDIS_HOST: redis
      CASBIN_MESH_REDIS_PORT: 6379
    ports:
      - "4002:4002"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: keycloak-container
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: start-dev

networks:
  default:
    external:
      name: bridge
#
#version: '3'
#services:
#  mysql:
#    image: mysql:latest
#    container_name: mysql-container
#    environment:
#      MYSQL_DATABASE: os.environ.get("MYSQL_DATABASE","weops_saas")
#      MYSQL_USER: os.environ.get("MYSQL_USER","root")
#      MYSQL_PASSWORD: os.environ.get("MYSQL_PASSWORD","jIUxdSqwQJss")
#    ports:
#      -
#        -
#          -
#      - "3306:3306"
#    volumes:
#      - /path/to/mysql/data:/var/lib/mysql
#
#  redis:
#    image: redis:latest
#    container_name: redis-container
#    ports:
#      - "6379:6379"
#
#  casbin-mesh:
#    image: casbin-mesh:latest
#    container_name: casbin-mesh-container
#    environment:
#      # Casbin Mesh configuration environment variables
#      CASBIN_MESH_DATABASE: mysql
#      CASBIN_MESH_DATABASE_CONNECTION_STRING: "mysql:mysql:3306?dbname=weops_saas&username=root&password=jIUxdSqwQJss"
#      CASBIN_MESH_REDIS_HOST: redis
#      CASBIN_MESH_REDIS_PORT: os.environ.get("MYSQL_PASSWORD","6379")
#    ports:
#      - "8000:8000"
#
#networks:
#  default:
#    external:
#      name: bridge